// TEMPORARY dev seed data — remove once real issues flow from Firestore.
// Used as a fallback in IssuesPage when the store is empty so the list view
// renders across multiple status/priority groups.
import { Timestamp } from 'firebase/firestore'
import type { Issue } from '@/types/issue'

const daysAgo = (n: number) => Timestamp.fromMillis(Date.now() - n * 86_400_000)

export const MOCK_ISSUES: Issue[] = [
  {
    id: 'mock-1',
    identifier: 'UIP-8',
    title: 'Submit form',
    description: '',
    status: 'in_progress',
    priority: 'no_priority',
    assigneeId: null,
    labelIds: [],
    projectId: null,
    milestoneId: null,
    cycleId: null,
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
    createdBy: 'mock-user',
  },
  {
    id: 'mock-2',
    identifier: 'UIP-2',
    title: 'Set up your teams',
    description: '',
    status: 'todo',
    priority: 'medium',
    assigneeId: null,
    labelIds: [],
    projectId: null,
    milestoneId: null,
    cycleId: null,
    createdAt: daysAgo(125),
    updatedAt: daysAgo(125),
    createdBy: 'mock-user',
  },
  {
    id: 'mock-3',
    identifier: 'UIP-3',
    title: 'Set up your teams',
    description: '',
    status: 'todo',
    priority: 'medium',
    assigneeId: null,
    labelIds: [],
    projectId: null,
    milestoneId: null,
    cycleId: null,
    createdAt: daysAgo(125),
    updatedAt: daysAgo(125),
    createdBy: 'mock-user',
  },
  {
    id: 'mock-4',
    identifier: 'UIP-4',
    title: 'Set up your teams',
    description: '',
    status: 'todo',
    priority: 'medium',
    assigneeId: null,
    labelIds: [],
    projectId: null,
    milestoneId: null,
    cycleId: null,
    createdAt: daysAgo(125),
    updatedAt: daysAgo(125),
    createdBy: 'mock-user',
  },
  {
    id: 'mock-5',
    identifier: 'UIP-5',
    title: 'Connect your tools',
    description: '',
    status: 'todo',
    priority: 'high',
    assigneeId: null,
    labelIds: [],
    projectId: null,
    milestoneId: null,
    cycleId: null,
    createdAt: daysAgo(125),
    updatedAt: daysAgo(125),
    createdBy: 'mock-user',
  },
  {
    id: 'mock-6',
    identifier: 'UIP-6',
    title: 'Import your data',
    description: '',
    status: 'todo',
    priority: 'low',
    assigneeId: null,
    labelIds: [],
    projectId: null,
    milestoneId: null,
    cycleId: null,
    createdAt: daysAgo(125),
    updatedAt: daysAgo(125),
    createdBy: 'mock-user',
  },
  {
    id: 'mock-7',
    identifier: 'UIP-9',
    title: 'new issue',
    description: '',
    status: 'backlog',
    priority: 'no_priority',
    assigneeId: null,
    labelIds: [],
    projectId: 'mock-project',
    milestoneId: null,
    cycleId: null,
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
    createdBy: 'mock-user',
  },
  {
    id: 'mock-8',
    identifier: 'UIP-6',
    title: 'new issue test',
    description: '',
    status: 'backlog',
    priority: 'urgent',
    assigneeId: 'mock-user',
    labelIds: [],
    projectId: null,
    milestoneId: null,
    cycleId: null,
    createdAt: daysAgo(105),
    updatedAt: daysAgo(105),
    createdBy: 'mock-user',
  },
  {
    id: 'mock-9',
    identifier: 'UIP-5',
    title: 'Test Issue',
    description: '',
    status: 'backlog',
    priority: 'medium',
    assigneeId: null,
    labelIds: ['feature'],
    projectId: null,
    milestoneId: null,
    cycleId: null,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(120),
    createdBy: 'mock-user',
  },
  {
    id: 'mock-10',
    identifier: 'UIP-7',
    title: 'new chec issue',
    description: '',
    status: 'done',
    priority: 'urgent',
    assigneeId: null,
    labelIds: [],
    projectId: null,
    milestoneId: null,
    cycleId: null,
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
    createdBy: 'mock-user',
  },
  {
    id: 'mock-11',
    identifier: 'UIP-1',
    title: 'Welcome to FluxFlow',
    description: '',
    status: 'done',
    priority: 'no_priority',
    assigneeId: null,
    labelIds: [],
    projectId: null,
    milestoneId: null,
    cycleId: null,
    createdAt: daysAgo(130),
    updatedAt: daysAgo(130),
    createdBy: 'mock-user',
  },
]
